name: Architecture-Specific Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  download-whisperkit-models:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      # Restore the models cache if it exists
      - name: Restore WhisperKit Models Cache
        id: whisperkit-cache
        uses: actions/cache@v3
        with:
          # You can adjust the path based on exactly where your models live
          path: WhisperKitAndroid/models
          key: ${{ runner.os }}-whisperkit-models-${{ hashFiles('WhisperKitAndroid/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-whisperkit-models-

      - name: Clone WhisperKitAndroid Repository
        if: steps.whisperkit-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/argmaxinc/WhisperKitAndroid.git
          cd WhisperKitAndroid
          make download-models

      # Optionally upload the models as an artifact. This is useful if you want
      # to inspect or download the models directly from the Actions run logs.
      - name: Upload WhisperKit Models Artifact
        uses: actions/upload-artifact@v4
        with:
          name: whisperkit-models
          path: WhisperKitAndroid/models

      # If the cache was not previously hit, update the cache now that models are downloaded
      - name: Update WhisperKit Models Cache
        if: steps.whisperkit-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: WhisperKitAndroid/models
          key: ${{ runner.os }}-whisperkit-models-${{ hashFiles('WhisperKitAndroid/Makefile') }}

  build-whisperkit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Clone the external repository and create the target directory
      - name: Clone WhisperKitAndroid Repository
        run: |
          git clone https://github.com/argmaxinc/WhisperKitAndroid.git

      # Restore cached artifacts from qairt/lib/external
      - name: Restore cached whisperkit artifacts
        id: cache-whisperkit
        uses: actions/cache@v3
        with:
          path: qairt/2.31.0/lib/external
          key: ${{ runner.os }}-whisperkit-${{ hashFiles('WhisperKitAndroid/jni/NativeWhisperKit.cpp', 'WhisperKitAndroid/scripts/dev_env.sh') }}

      - name: Update NativeWhisperKit.cpp Function Names
        working-directory: WhisperKitAndroid
        run: |
          sed -i 's/Java_com_argmaxinc_WhisperKitNative/Java_com_edgeai_chatappv2_WhisperKitNative/g' jni/NativeWhisperKit.cpp

      - name: Update QNN SDK Version in dev_env.sh and Dockerfile
        working-directory: WhisperKitAndroid
        run: |
          sed -i \
            -e 's#/qnn-runtime/2\.27\.0/qnn-runtime-2\.27\.0\.aar#/qnn-runtime/2.31.0/qnn-runtime-2.31.0.aar#g' \
            -e 's#/qnn-tflite-delegate/2\.27\.0/qnn-tflite-delegate-2\.27\.0\.aar#/qnn-litert-delegate/2.31.0/qnn-litert-delegate-2.31.0.aar#g' \
            -e 's/qnn-runtime-2\.27\.0\.aar/qnn-runtime-2.31.0.aar/g' \
            -e 's/qnn-tflite-delegate-2\.27\.0\.aar/qnn-litert-delegate-2.31.0.aar/g' \
            scripts/dev_env.sh scripts/Dockerfile

      - name: Build Dev Environment & JNI Libraries (.so Files)
        working-directory: WhisperKitAndroid
        if: steps.cache-whisperkit.outputs.cache-hit != 'true'
        run: |
          make ci-env
          docker exec axie_tflite make build jni
          docker exec axie_tflite ls .
          docker exec axie_tflite pwd

      # Copy the built libraries to the target directory in the repository
      - name: Copy shared libraries to target directory
        if: steps.cache-whisperkit.outputs.cache-hit != 'true'
        working-directory: WhisperKitAndroid
        run: |
          mkdir -p ../qairt/2.31.0/lib/external
          cp external/libs/android/libavcodec.so ../qairt/2.31.0/lib/external/
          cp external/libs/android/libavformat.so ../qairt/2.31.0/lib/external/
          cp external/libs/android/libavutil.so ../qairt/2.31.0/lib/external/
          cp external/libs/android/libqnn_delegate_jni.so ../qairt/2.31.0/lib/external/
          cp external/libs/android/libSDL3.so ../qairt/2.31.0/lib/external/
          cp external/libs/android/libswresample.so ../qairt/2.31.0/lib/external/
          cp external/libs/android/libtensorflowlite.so ../qairt/2.31.0/lib/external/
          cp external/libs/android/libtensorflowlite_gpu_delegate.so ../qairt/2.31.0/lib/external/
          cp build/android/libwhisperkit.so ../qairt/2.31.0/lib/external/
          cp build/android/libnative-whisper.so ../qairt/2.31.0/lib/external/

      # Save the final built artifacts (under qairt/lib/external) to cache
      - name: Save whisperkit artifacts to cache
        if: steps.cache-whisperkit.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: qairt/2.31.0/lib/external
          key: ${{ runner.os }}-whisperkit-${{ hashFiles('WhisperKitAndroid/jni/NativeWhisperKit.cpp', 'WhisperKitAndroid/scripts/dev_env.sh') }}

      - name: Upload whisperkit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cache-whisperkit
          path: qairt/2.31.0/lib/external/
  
  sherpa-build:
    runs-on: ubuntu-latest
    env:
      QNN_SDK_PATH: /opt/qcom/aitstack/qairt/2.31.0
      ANDROID_NDK: /Users/fangjun/software/my-android/ndk/28.x.x
      ANDROID_PROJECT_PATH: /path/to/your/android-project  # Update this path as needed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git sudo

      - name: Install Android NDK
        run: |
          # Download Android NDK (r27b for Linux is used as an example)
          curl -L https://dl.google.com/android/repository/android-ndk-r27b-linux.zip -o ndk.zip
          unzip ndk.zip -d $HOME/android-ndk
          # Export the ANDROID_NDK path so subsequent steps can use it
          echo "ANDROID_NDK=$HOME/android-ndk/android-ndk-r27b" >> $GITHUB_ENV
          echo "Installed Android NDK at $HOME/android-ndk/android-ndk-r27b"

      - name: Restore built libraries cache
        id: cache-libs
        uses: actions/cache@v3
        with:
          path: cached_libs
          key: ${{ runner.os }}-build-cache-${{ github.ref }}

      - name: Clone sherpa-onnx-qnn repository
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/mjnong/sherpa-onnx-qnn.git

      - name: Download ONNX QNN support files
        if: steps.cache-libs.outputs.cache-hit != 'true'
        working-directory: sherpa-onnx-qnn
        run: |
          ./scripts/qairt/download_onnx_qnn.sh

      - name: Build for Android (arm64-v8a)
        if: steps.cache-libs.outputs.cache-hit != 'true'
        working-directory: sherpa-onnx-qnn
        run: |
          chmod +x build-android-arm64-v8a.sh
          ./build-android-arm64-v8a.sh

      - name: Prepare cache folder for built libraries
        if: steps.cache-libs.outputs.cache-hit != 'true'
        run: |
          mkdir -p cached_libs
          cp sherpa-onnx-qnn/build-android-arm64-v8a/install/lib/libonnxruntime.so cached_libs/
          cp sherpa-onnx-qnn/build-android-arm64-v8a/install/lib/libsherpa-onnx-jni.so cached_libs/

      - name: Update built libraries cache
        if: steps.cache-libs.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: cached_libs
          key: ${{ runner.os }}-build-cache-${{ github.ref }}

      - name: Upload built libraries artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-libraries
          path: cached_libs/

  build-app:
    runs-on: ubuntu-latest
    needs: [ build-whisperkit, sherpa-build, download-whisperkit-models ]
    strategy:
      matrix:
        hexagon: [ hexagon-v75, hexagon-v79 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create paths
        run: |
          mkdir -p qairt/

      - name: Clone sherpa-onnx-qnn repository
        run: |
          git clone https://github.com/mjnong/sherpa-onnx-qnn.git

      # Download release asset only if cache was not found
      - name: Download release asset
        run: |
          gh release download v0.0.1 -p 'qairt.zip'
          unzip -o "qairt.zip" -d .
          rm qairt.zip
          ls qairt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up swap file
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
      
      - name: Download whisperkit artifact (external)
        uses: actions/download-artifact@v4
        with:
          name: cache-whisperkit
          path: qairt/lib/external/

      - name: Download whisperkit models
        uses: actions/download-artifact@v4
        with:
          name: whisperkit-models
          path: app/src/main/assets/

      - name: Restore built libraries cache
        id: cache-libs
        uses: actions/cache@v3
        with:
          path: cached_libs
          key: ${{ runner.os }}-build-cache-${{ github.ref }}

      - name: List contents of artifact folders
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          rm -r qairt/2.31.0/lib/hexagon-v73-securepd
          rm -r qairt/2.31.0/lib/hexagon-v75-securepd
          rm -r qairt/2.31.0/lib/hexagon-v79-securepd
          rm -r qairt/2.31.0/lib/arm64x-windows-msvc
          rm -r qairt/2.31.0/lib/aarch64-ubuntu-gcc9.4
          rm -r qairt/2.31.0/lib/aarch64-oe-linux-gcc9.3
          rm -r qairt/2.31.0/lib/aarch64-oe-linux-gcc11.2
          rm -r qairt/2.31.0/lib/python

          mkdir -p app/src/main/cpp/include
          cp -r qairt/2.31.0/include/Genie/* app/src/main/cpp/include

          pwd
          ls
          echo ""
          echo "Contents of qairt/2.31.0/lib/${{ matrix.hexagon }}/unsigned/"
          ls qairt/2.31.0/lib/${{ matrix.hexagon }}/unsigned/

          echo ""
          echo "Contents of app/src/main/cpp/include"
          ls app/src/main/cpp/include

          echo ""
          echo "Contents of qairt/2.31.0/lib/aarch64-android/"
          ls qairt/2.31.0/lib/aarch64-android/
          
          echo ""
          echo "Contents of qairt/2.31.0/lib/external"
          ls qairt/2.31.0/lib/external

          # .bin models, tokenizer, genie config
          gh release download v0.0.1 -p '*.bin' --dir app/src/main/assets/models/llama3_2_3b
          gh release download v0.0.1 -p 'tokenizer.json' --dir app/src/main/assets/models/llama3_2_3b
          gh release download v0.0.1 -p 'genie_config.json' --dir app/src/main/assets/models/llama3_2_3b

          # hexagon config
          gh release download v0.0.1 -p 'htp_backend_ext_config.json' --dir app/src/main/assets/htp_config

          echo ""
          echo "Contents of app/src/main/assets/models"
          ls app/src/main/assets/models

          cp cached_libs/libonnxruntime.so /home/runner/work/chatapp-v2/chatapp-v2/qairt/2.31.0/lib/external/
          cp cached_libs/libsherpa-onnx-jni.so /home/runner/work/chatapp-v2/chatapp-v2/qairt/2.31.0/lib/external/
          ls -la /home/runner/work/chatapp-v2/chatapp-v2/qairt/2.31.0/lib/external/
          ln -s /home/runner/work/chatapp-v2/chatapp-v2/sherpa-onnx-qnn/sherpa-onnx/kotlin-api/Tts.kt /home/runner/work/chatapp-v2/chatapp-v2/app/src/main/java/com/edgeai/chatappv2/Tts.kt


      - name: Build app
        run: ./gradlew :app:clean :app:assembleDebug :app:assembleDebugUnitTest :app:assembleDebugAndroidTest

