name: Download and Extract Release Assets

on:
  workflow_dispatch:
  pull_request:

jobs:
  download_and_extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download release assets (excluding source code)
        run: |
          # List all asset names from the release that do NOT contain "Source code"
          assets=$(gh release view v0.0.1 --json assets --jq '.assets[] | select(.name | index("Source code") | not) | .name')
          echo "Assets to download:"
          echo "$assets"
          # Download each asset individually
          for asset in $assets; do
            echo "Downloading $asset"
            gh release download v0.0.1 -p "$asset"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract zip files
        run: |
          mkdir -p app/src/main/jniLibs/
          for file in *.zip; do
            echo "Extracting $file..."
            unzip "$file" -d app/src/main/jniLibs/"${file%.*}"
          done

      - name: Upload extracted artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extracted-files
          path: app/src/main/jniLibs/


  build:
    needs: download_and_extract
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: ["gen3", "8elite"]
        include:
          - architecture: gen3
            hexagon_files: extracted/hexagon-v75
          - architecture: 8elite
            hexagon_files: extracted/hexagon-v79
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Download extracted artifacts
        uses: actions/download-artifact@v4
        with:
          name: extracted-files
          path: extracted/
      
      - name: Build for ${{ matrix.architecture }}
        run: |
          echo "Building for ${{ matrix.architecture }} using ${{ matrix.hexagon_files }}"
          # Example build command using the hexagon file
          echo "Using common aarch64-android files from extracted/aarch64-android"
          # Your build command here