name: Architecture-Specific Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache the extracted artifact directories
      - name: Cache architecture artifacts
        id: cache-artifacts
        uses: actions/cache@v3
        with:
          path: |
            aarch64-android
            hexagon-v75
            hexagon-v79
          # Use a cache key that makes sense for your use case.
          # For example, you might use the branch name or a hash of the release tag.
          key: ${{ runner.os }}-architecture-artifacts-${{ github.ref }}

      # Only download the release assets if the cache was not found
      - name: Download release assets
        if: steps.cache-artifacts.outputs.cache-hit != 'true'
        run: gh release download v0.0.1 -p '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only extract the artifacts if the cache was not found
      - name: Extract and create component artifacts
        if: steps.cache-artifacts.outputs.cache-hit != 'true'
        run: |
          # Create temporary directories
          mkdir -p {aarch64-android,hexagon-v75,hexagon-v79}
  
          # Extract files from the downloaded zips
          for zip in *.zip; do
            case "$zip" in
              aarch64-android.zip)
                unzip -j "$zip" 'aarch64-android/*' -d aarch64-android/
                ;;
              hexagon-v75.zip)
                unzip -j "$zip" 'hexagon-v75/*' -d hexagon-v75/
                ;;
              hexagon-v79.zip)
                unzip -j "$zip" 'hexagon-v79/*' -d hexagon-v79/
                ;;
            esac
          done
  
          # Display component sizes
          echo "Component sizes:"
          du -sh {aarch64-android,hexagon-v75,hexagon-v79}

      # Regardless of cache, upload the artifacts so that downstream jobs can use them
      - name: Upload aarch64-android artifact
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-android
          path: aarch64-android/

      - name: Upload hexagon-v75 artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexagon-v75
          path: hexagon-v75/

      - name: Upload hexagon-v79 artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexagon-v79
          path: hexagon-v79/

  build-whisperkit:
    runs-on: ubuntu-latest
    steps:
      # Clone the external repository
      - name: Clone WhisperKitAndroid Repository
        run: git clone https://github.com/argmaxinc/WhisperKitAndroid.git

      # Restore cached jni-libs based on changes in the JNI source file
      - name: Restore cached jni-libs
        id: cache-jni-libs
        uses: actions/cache@v3
        with:
          path: WhisperKitAndroid/external/libs/android
          key: ${{ runner.os }}-jni-libs-${{ hashFiles('WhisperKitAndroid/jni/NativeWhisperKit.cpp') }}

      # Restore cached whisperkit-libs based on changes in the build environment config
      - name: Restore cached whisperkit-libs
        id: cache-whisperkit-libs
        uses: actions/cache@v3
        with:
          path: WhisperKitAndroid/build/android
          key: ${{ runner.os }}-whisperkit-libs-${{ hashFiles('WhisperKitAndroid/scripts/dev_env.sh') }}

      # Update JNI function names as needed
      - name: Update NativeWhisperKit.cpp Function Names
        working-directory: WhisperKitAndroid
        run: |
          sed -i 's/Java_com_argmaxinc_WhisperKitNative/Java_com_edgeai_chatappv2_WhisperKitNative/g' jni/NativeWhisperKit.cpp

      # Update QNN SDK versions in the dev environment scripts and Dockerfile
      - name: Update QNN SDK Version in dev_env.sh and Dockerfile
        working-directory: WhisperKitAndroid
        run: |
          sed -i \
            -e 's#/qnn-runtime/2\.27\.0/qnn-runtime-2\.27\.0\.aar#/qnn-runtime/2.31.0/qnn-runtime-2.31.0.aar#g' \
            -e 's#/qnn-tflite-delegate/2\.27\.0/qnn-tflite-delegate-2\.27\.0\.aar#/qnn-tflite-delegate/2\.31\.0/qnn-tflite-delegate-2.31.0.aar#g' \
            scripts/dev_env.sh scripts/Dockerfile

      # Build the dev environment and JNI libraries if either cache is missing
      - name: Build Dev Environment & JNI Libraries (.so Files)
        working-directory: WhisperKitAndroid
        if: steps.cache-jni-libs.outputs.cache-hit != 'true' || steps.cache-whisperkit-libs.outputs.cache-hit != 'true'
        run: |
          make ci-env
          docker exec axie_tflite make build jni

      # Save updated jni-libs to cache if they were rebuilt
      - name: Save jni-libs to cache
        if: steps.cache-jni-libs.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: WhisperKitAndroid/external/libs/android
          key: ${{ runner.os }}-jni-libs-${{ hashFiles('WhisperKitAndroid/jni/NativeWhisperKit.cpp') }}

      # Save updated whisperkit-libs to cache if they were rebuilt
      - name: Save whisperkit-libs to cache
        if: steps.cache-whisperkit-libs.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: WhisperKitAndroid/build/android
          key: ${{ runner.os }}-whisperkit-libs-${{ hashFiles('WhisperKitAndroid/scripts/dev_env.sh') }}